Added seccomp profile support
adobe-platform/dcos-scripts pull request #14
Opened 2017-01-28 01:23 UTC by kravivar

@matthewdfuller : Please review

CC: @anshupande 

Fixes : https://github.com/adobe-community/issues-ethos/issues/1645

2017-01-28 01:24 UTC, kravivar commented
Fixes : https://github.com/adobe-community/issues-ethos/issues/2546

2017-01-30 16:23 UTC, matthewdfuller commented
@kravivar - can you hardcode the JSON into the script? Reason being is that the script is loaded into the Mesos execution environment [here](https://git.corp.adobe.com/adobe-platform/dcos-universe-private/blob/ethos-1.x-unstable/repo/packages/A/aqua-ethos-setup/0/marathon.json.mustache#L6). Since it's pretty short, we can get away with just using `EOF` and not having to download two files.

2017-01-30 16:23 UTC, matthewdfuller commented
Also, once I merge this in, can you submit an update for the above package?

2017-02-12 23:21 UTC, kravivar commented
@matthewdfuller : Updated the contents as per recommendation

2017-02-13 21:26 UTC, matthewdfuller commented on aqua-ethos-setup/aqua_ethos.sh
> +{"defaultAction":"SCMP_ACT_ERRNO","syscalls":[{"names":["capget","capset","chdir","fchown","futex","getdents64","getpid","getppid","lstat","openat","prctl","setgid","setgroups","setuid","stat","rt_si
Sorry to be nitpicky on this, but can you use the same spacing/line breaks as you do below? It makes it very hard to read/update in the future as one big line.

2017-02-13 21:28 UTC, matthewdfuller requested changes
Please include this rule check in the loop at the end as well:

https://github.com/kravivar/dcos-scripts/blob/776e4bf64ef955e71fd22f1dabd2ff678ecc9507/aqua-ethos-setup/aqua_ethos.sh#L100

I would rename `EXISTING_RULE` for your addition to `EXISTING_SECOMP_RULE` or something similar

2017-02-14 19:43 UTC, kravivar commented
@matthewdfuller I have made the changes you wanted, please review.

2017-02-21 15:01 UTC, matthewdfuller requested changes
The recent changes broke existing work. We don't want to _replace_ `EXISTING_RULE`, we want to add a _new_ item for `EXISTING_SECOMP_RULE`. Please make these changes so we are testing both.

2017-02-21 15:01 UTC, matthewdfuller commented on aqua-ethos-setup/aqua_ethos.sh
> +EXISTING_SECOMP_RULE=$(curl --write-out %{http_code} --silent --output /dev/null -H "$HEADER: Bearer $TOKEN" $WEB_URL/adminrules/core-user-rule)
@kravivar - why are you overwriting the existing rule `EXISTING_RULE` with `EXISTING_SECOMP_RULE` when `EXISTING_SECOMP_RULE` already exists above (see line 67)?

2017-02-21 15:01 UTC, matthewdfuller commented on aqua-ethos-setup/aqua_ethos.sh
> +if [[ "$EXISTING_SECOMP_RULE" == "200" ]]; then
This should go back to `EXISTING_RULE`

2017-02-21 15:01 UTC, matthewdfuller commented on aqua-ethos-setup/aqua_ethos.sh
> +while [[ "$EXISTING_PROFILE" == "200" && "$EXISTING_SECOMP_RULE" == "200" ]]; do
This should become:
```
while [[ "$EXISTING_PROFILE" == "200" && "$EXISTING_PROFILE" == "200" && "$EXISTING_SECOMP_RULE" == "200" ]]; do
```

2017-02-21 15:01 UTC, matthewdfuller commented on aqua-ethos-setup/aqua_ethos.sh
> +	EXISTING_SECOMP_RULE=$(curl --write-out %{http_code} --silent --output /dev/null -H "$HEADER: Bearer $TOKEN" $WEB_URL/adminrules/core-user-rule)
This should be an addition not a change

2017-02-21 15:01 UTC, matthewdfuller commented on aqua-ethos-setup/aqua_ethos.sh
> +	if [[ "$EXISTING_SECOMP_RULE" == "200" && "$EXISTING_PROFILE" == "200" ]]; then
This should be:
```
if [[ "$EXISTING_RULE" == "200" && "$EXISTING_SECOMP_RULE" == "200" && "$EXISTING_PROFILE" == "200" ]]; then
```

2017-03-06 14:17 UTC, matthewdfuller commented
@kravivar - ping on these updates

2017-03-16 17:26 UTC, closed without merging