add production approved label
adobe-platform/dcos-scripts pull request #18
Opened 2017-02-17 20:22 UTC by anshupande

2017-02-17 20:27 UTC, iderdik commented on aqua-ethos-setup/aqua_ethos.sh
> +	curl --silent -H "Accept: application/json" -H "Content-type: application/json" -H "$HEADER: Bearer $TOKEN" -X POST -d '{"name": "production approved", "description": "production approved images"}'
We also need to attach the policy to it tat whitelists the images

2017-02-17 21:01 UTC, anshupande commented on aqua-ethos-setup/aqua_ethos.sh
> +	curl --silent -H "Accept: application/json" -H "Content-type: application/json" -H "$HEADER: Bearer $TOKEN" -X POST -d '{"name": "production approved", "description": "production approved images"}'
Which API call are you referring to here?

2017-02-17 21:01 UTC, anshupande commented on aqua-ethos-setup/aqua_ethos.sh
> +	curl --silent -H "Accept: application/json" -H "Content-type: application/json" -H "$HEADER: Bearer $TOKEN" -X POST -d '{"name": "production approved", "description": "production approved images"}'
You mean these steps ? - Create a label (this is done)/ Attach it to image(?): https://docs.aquasec.com/v2.0/docs/labels
Creating a host batch install(?):
https://docs.aquasec.com/v2.0/docs/batch-install (there is a policy on the host for allowed labels).

2017-02-17 21:04 UTC, iderdik commented on aqua-ethos-setup/aqua_ethos.sh
> +	curl --silent -H "Accept: application/json" -H "Content-type: application/json" -H "$HEADER: Bearer $TOKEN" -X POST -d '{"name": "production approved", "description": "production approved images"}'
A policy must be created to:
1. Block all images from running
2. allow images that have "production approved" labels to run

FD will handle associating images to the "production approved" label. However, you need to create the policy along with the label.

2017-02-21 15:04 UTC, matthewdfuller requested changes

2017-02-21 15:04 UTC, matthewdfuller commented on aqua-ethos-setup/aqua_ethos.sh
> +curl --silent -H "$HEADER: Bearer $TOKEN" -X POST -d '{"only_registered_images":true,"daily_scan_enabled":true,"daily_scan_time":{"hour":1,"minute":0,"second":0},"average_score_enabled":false,"averag
Indentation

2017-02-21 15:04 UTC, matthewdfuller commented on aqua-ethos-setup/aqua_ethos.sh
> +while [[ "$EXISTING_PROFILE" == "200" && "EXISTING_LABEL" == "200" && "$EXISTING_RULE" == "200" ]]; do
We should add `IMAGE_ASSURANCE` here as well

2017-02-21 15:50 UTC, anshupande commented on aqua-ethos-setup/aqua_ethos.sh
> +	curl --silent -H "Accept: application/json" -H "Content-type: application/json" -H "$HEADER: Bearer $TOKEN" -X POST -d '{"name": "production approved", "description": "production approved images"}'
added 2 - allow images that have "production approved" labels to run

2017-02-25 16:18 UTC, matthewdfuller requested changes

2017-02-25 16:18 UTC, matthewdfuller commented on aqua-ethos-setup/aqua_ethos.sh
> +	curl --silent -H "Accept: application/json" -H "Content-type: application/json" -H "$HEADER: Bearer $TOKEN" -X POST -d  '{"prefixes": [], "auto_pull": false, "auto_pull_time": "03:00", "auto_pull_ma
Let's stick with capital letters for the env variables: `$ARTIFACTORY_URL`, `$ARTIFACTORY_USERNAME`, etc.

2017-03-07 14:45 UTC, matthewdfuller commented
Is this PR going to block our admin apps? I don't see any place where we are whitelisting those, even though they won't have the whitelist label

2017-03-08 01:09 UTC, anshupande commented
We need to add a label `production approved` and avoid the API to whitelist the admin images as scanning them will waste lot of time. This is being followed here with aqua: https://support.aquasec.com/helpdesk/tickets/77

2017-03-08 17:23 UTC, msabramo commented
<Pie in the sky stuff requires="aqua-support">
Instead of using labels (that we have to apply when we deploy a container with the image), what if we could do something when we build the image that whitelists it. For example, what if instead we put a file into the image that is cryptographically signed with an [HMAC](https://en.wikipedia.org/wiki/Hash-based_message_authentication_code) and secret key? By putting a file into the image that is signed with our key, we are authenticating that the image is from us. Then Aqua could scan the image and look for this file and verify that it's signed properly and then maybe add the label itself.

The neat thing is that none of this needs to happen at deploy-time; it can happen at image build-time, so then it's out of the way by time we deploy.
</Pie in the sky stuff>

2017-03-08 17:40 UTC, msabramo commented
Hmmm, just found this: https://docs.docker.com/engine/security/trust/content_trust/#image-tags-and-content-trust

2017-03-20 14:07 UTC, matthewdfuller commented on aqua-ethos-setup/aqua_ethos.sh
> +	curl --silent -H "Accept: application/json" -H "Content-type: application/json" -H "$HEADER: Bearer $TOKEN" -X POST -d  '{"prefixes": [], "auto_pull": false, "auto_pull_time": "03:00", "auto_pull_ma
This will not work because you are using variables inside of single quotes in bash

2017-03-21 14:12 UTC, matthewdfuller commented
I've pulled out the artifactory-specific work here: https://github.com/adobe-platform/dcos-scripts/pull/31

I am closing this because the file and setup has changed significantly.

Once Aqua 2.1 is tested, please submit a new PR for just the image assurance and label aspects of this PR. Do not duplicate the artifactory work from #31

2017-03-21 14:12 UTC, closed without merging